[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 3

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 4
#
# [[main]]
#     identifier = "tags"
#     name = "Tags"
#     url = "/tags"
#     weight = 4
#
# [[main]]
#     identifier = "donate"
#     name = "Donate"
#     url = "https://ko-fi.com/nixentric"
#     weight = 5
    
# Social Media Configuration



[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/jkausti"
    weight = 1

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/johnkaustinen/"
    weight = 2
